#! /usr/bin/env bash
set -e
set -u
source $(cd "$(dirname $0)" && pwd)/env.sh

$RAMCLOUD_ROOT/obj.$GIT_BRANCH/coordinator \
    -C infrc:host=ifrit.cc.gt.atl.ga.us,port=11100,devport=$IB_PORT \
    -x zk:$ZKSERVER:2181

